// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD530FLwl-9u8-3VxlVaSsYuYTdokhTLtE',
    appId: '1:978027561410:web:ea9730af48b4efbf5bd65b',
    messagingSenderId: '978027561410',
    projectId: 'test-flutter-ndh',
    authDomain: 'test-flutter-ndh.firebaseapp.com',
    storageBucket: 'test-flutter-ndh.appspot.com',
    measurementId: 'G-YX9QMP9MEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv4iVhoY0z8xKV7u7kD88to9fmI8bxsjk',
    appId: '1:978027561410:android:03bc152cc289523d5bd65b',
    messagingSenderId: '978027561410',
    projectId: 'test-flutter-ndh',
    storageBucket: 'test-flutter-ndh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfeT6JGfBeVItJmV2IxZbXCWmRaO1OssY',
    appId: '1:978027561410:ios:374b76f4b17b97a15bd65b',
    messagingSenderId: '978027561410',
    projectId: 'test-flutter-ndh',
    storageBucket: 'test-flutter-ndh.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfeT6JGfBeVItJmV2IxZbXCWmRaO1OssY',
    appId: '1:978027561410:ios:491311ddbe9ad4595bd65b',
    messagingSenderId: '978027561410',
    projectId: 'test-flutter-ndh',
    storageBucket: 'test-flutter-ndh.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
